export const mockClasses = [
  {
    id: '1',
    title: 'Regangkan Leher & Bahu',
    description: 'Yoga cepat untuk meredakan ketegangan leher dan bahu akibat duduk lama.',
    duration_min: 7,
    level: 'Pemula',
    category: 'quick_fix',
    complaints: ['Leher & Bahu'],
    location: 'Di meja',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail_url: 'https://picsum.photos/seed/yoga1/400/225',
    is_premium: false,
    instructor: { id: '1', name: 'Sari Dewi', avatar_url: 'https://i.pravatar.cc/64?img=1' },
  },
  {
    id: '2',
    title: 'Relaksasi Punggung Bawah',
    description: 'Gerakan lembut untuk punggung bawah yang tegang karena duduk seharian.',
    duration_min: 10,
    level: 'Pemula',
    category: 'pagi',
    complaints: ['Punggung Bawah'],
    location: 'Kursi',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail_url: 'https://picsum.photos/seed/yoga2/400/225',
    is_premium: false,
    instructor: { id: '2', name: 'Budi Santoso', avatar_url: 'https://i.pravatar.cc/64?img=2' },
  },
  {
    id: '3',
    title: 'Meditasi Singkat untuk Stres',
    description: 'Teknik pernapasan dan meditasi untuk menenangkan pikiran di tengah kesibukan.',
    duration_min: 5,
    level: 'Semua Level',
    category: 'quick_fix',
    complaints: ['Stres & Mental'],
    location: 'Di meja',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://picsum.photos/seed/yoga3/400/225',
    is_premium: false,
    instructor: { id: '1', name: 'Sari Dewi', avatar_url: 'https://i.pravatar.cc/64?img=1' },
  },
  {
    id: '4',
    title: 'Yoga Mata Lelah',
    description: 'Latihan khusus untuk merilekskan mata setelah menatap layar terlalu lama.',
    duration_min: 7,
    level: 'Pemula',
    category: 'siang',
    complaints: ['Mata Lelah'],
    location: 'Di meja',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail_url: 'https://picsum.photos/seed/yoga4/400/225',
    is_premium: true,
    instructor: { id: '2', name: 'Budi Santoso', avatar_url: 'https://i.pravatar.cc/64?img=2' },
  },
  {
    id: '5',
    title: 'Full Body Morning Flow',
    description: 'Rangkaian yoga pagi yang menyegarkan untuk memulai hari dengan energi penuh.',
    duration_min: 25,
    level: 'Menengah',
    category: 'pagi',
    complaints: ['Punggung Bawah', 'Leher & Bahu'],
    location: 'Lantai',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail_url: 'https://picsum.photos/seed/yoga5/400/225',
    is_premium: true,
    instructor: { id: '3', name: 'Lisa Putri', avatar_url: 'https://i.pravatar.cc/64?img=3' },
  },
  {
    id: '6',
    title: 'Evening Wind Down',
    description: 'Yoga malam yang lembut untuk persiapan tidur berkualitas.',
    duration_min: 15,
    level: 'Pemula',
    category: 'malam',
    complaints: ['Kualitas Tidur', 'Stres & Mental'],
    location: 'Kasur',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnail_url: 'https://picsum.photos/seed/yoga6/400/225',
    is_premium: false,
    instructor: { id: '1', name: 'Sari Dewi', avatar_url: 'https://i.pravatar.cc/64?img=1' },
  },
  {
    id: '7',
    title: 'Peregangan Pergelangan Tangan',
    description: 'Latihan khusus untuk pergelangan tangan yang sering pegal akibat mengetik.',
    duration_min: 5,
    level: 'Pemula',
    category: 'quick_fix',
    complaints: ['Pergelangan Tangan'],
    location: 'Di meja',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnail_url: 'https://picsum.photos/seed/yoga7/400/225',
    is_premium: false,
    instructor: { id: '2', name: 'Budi Santoso', avatar_url: 'https://i.pravatar.cc/64?img=2' },
  },
  {
    id: '8',
    title: 'Weekend Deep Stretch',
    description: 'Sesi yoga akhir pekan yang lebih panjang untuk pemulihan penuh.',
    duration_min: 30,
    level: 'Menengah',
    category: 'weekend',
    complaints: ['Punggung Bawah', 'Leher & Bahu', 'Kualitas Tidur'],
    location: 'Lantai',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnail_url: 'https://picsum.photos/seed/yoga8/400/225',
    is_premium: true,
    instructor: { id: '3', name: 'Lisa Putri', avatar_url: 'https://i.pravatar.cc/64?img=3' },
  },
];

export const mockPrograms = [
  {
    id: 'prog_1',
    title: 'Bebaskan Punggungmu',
    icon: '🧘',
    total_days: 7,
    minutes_per_day: 10,
    description: 'Program 7 hari untuk membebaskan punggung bawah dari rasa sakit akibat duduk terlalu lama.',
    complaint: 'Punggung Bawah',
    is_premium: false,
    status: 'active',
    current_day: 3,
  },
  {
    id: 'prog_2',
    title: 'Leher Bebas, Pikiran Jernih',
    icon: '🌿',
    total_days: 5,
    minutes_per_day: 7,
    description: 'Bebaskan leher dan bahu dari ketegangan, sekaligus jernih pikiran.',
    complaint: 'Leher & Bahu',
    is_premium: false,
    status: 'not_started',
    current_day: 0,
  },
  {
    id: 'prog_3',
    title: 'Stress Reset',
    icon: '🧠',
    total_days: 7,
    minutes_per_day: 12,
    description: 'Reset mental dan kurangi stres dengan program meditasi dan yoga 7 hari.',
    complaint: 'Stres & Mental',
    is_premium: true,
    status: 'locked',
    current_day: 0,
  },
  {
    id: 'prog_4',
    title: 'Mata & Pikiran Segar',
    icon: '👁️',
    total_days: 5,
    minutes_per_day: 8,
    description: 'Program 5 hari untuk merilekskan mata dan menjaga kesehatan mata dari layar.',
    complaint: 'Mata Lelah',
    is_premium: true,
    status: 'locked',
    current_day: 0,
  },
  {
    id: 'prog_5',
    title: 'Tangan Sehat',
    icon: '🤲',
    total_days: 5,
    minutes_per_day: 5,
    description: 'Jaga kesehatan pergelangan tangan dengan program 5 hari yang mudah dilakukan.',
    complaint: 'Pergelangan Tangan',
    is_premium: true,
    status: 'locked',
    current_day: 0,
  },
];

export const getClasses = async () => mockClasses;
export const getPrograms = async () => mockPrograms;
export const getRecommendedPrograms = async () =>
  mockPrograms.filter((p) => p.status === 'not_started').slice(0, 2);
export const getClassById = async (id: string) => mockClasses.find((c) => c.id === id) ?? null;
export const getRecommendedClasses = async () => mockClasses.slice(0, 3);
